version: '3'
services:
  app:
    image: node:18.15.0-slim
    working_dir: /app
    volumes:
      - ../../:/app
    ports:
      - '3000:3000'
    command: sh -c "apt-get update && apt-get install -y procps && npm run start:dev"
  msqldatabase:
    container_name: 'mysql-db'
    image: mysql:8.0
    restart: always
    command: mysqld --sql_mode="IGNORE_SPACE,STRICT_TRANS_TABLES"
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/var/lib/mysql
networks:
  dev-net:
    driver: bridge
